name: TESTS

on:
  push:
    branches: [ "main", develop ]
  pull_request:
    branches: [ "main", develop ]
jobs:
  work_test:
      runs-on: ubuntu-latest
      steps:
        - name: Test add func 
          run: python3 -m unittest .github/workflow/test
